import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import type { CommandResult } from "@bindings/CommandResult";
import type { CrossSigningStatusSummary } from "@bindings/CrossSigningStatusSummary";
import type { DiscoverHomeserverResponse } from "@bindings/DiscoverHomeserverResponse";
import type { EmojiPair } from "@bindings/EmojiPair";
import type { EventReceipt } from "@bindings/EventReceipt";
import type { LoginRequest } from "@bindings/LoginRequest";
import type { LoginResponse } from "@bindings/LoginResponse";
import type { MediaContent } from "@bindings/MediaContent";
import type { PresenceStateDto } from "@bindings/PresenceStateDto";
import type { PresenceUpdate } from "@bindings/PresenceUpdate";
import type { QrLoginProgressEvent } from "@bindings/QrLoginProgressEvent";
import type { ReactionGroup } from "@bindings/ReactionGroup";
import type { ReactionToggleResult } from "@bindings/ReactionToggleResult";
import type { ReceiptTypeDto } from "@bindings/ReceiptTypeDto";
import type { ReceiptUpdate } from "@bindings/ReceiptUpdate";
import type { RegisterRequest } from "@bindings/RegisterRequest";
import type { ReplyRef } from "@bindings/ReplyRef";
import type { RoomMemberSummary } from "@bindings/RoomMemberSummary";
import type { RoomMessageSummary } from "@bindings/RoomMessageSummary";
import type { RoomSummary } from "@bindings/RoomSummary";
import type { RoomTimelineUpdate } from "@bindings/RoomTimelineUpdate";
import type { SasUpdateEvent } from "@bindings/SasUpdateEvent";
import type { SendQueueUpdateEvent } from "@bindings/SendQueueUpdateEvent";
import type { SendState } from "@bindings/SendState";
import type { SlashCommand } from "@bindings/SlashCommand";
import type { SpaceChild } from "@bindings/SpaceChild";
import type { SpaceJoinRule } from "@bindings/SpaceJoinRule";
import type { SyncStateEvent } from "@bindings/SyncStateEvent";
import type { TimelinePage } from "@bindings/TimelinePage";
import type { TypingUpdate } from "@bindings/TypingUpdate";
import type { UploadProgress } from "@bindings/UploadProgress";
import type { VerificationRequestSummary } from "@bindings/VerificationRequestSummary";

/**
 * IPC types are generated from the Rust structs by ts-rs — see
 * `src-tauri/src/bindings/`, regenerated by `cargo test --lib` and drift-checked in CI
 * (any uncommitted change fails the build). They're re-exported here so the rest of the
 * frontend imports the IPC types and their `invoke`/`listen` wrappers from one place;
 * do not redefine them by hand.
 */
export type {
  CommandResult,
  CrossSigningStatusSummary,
  DiscoverHomeserverResponse,
  EmojiPair,
  EventReceipt,
  LoginRequest,
  LoginResponse,
  MediaContent,
  PresenceStateDto,
  PresenceUpdate,
  QrLoginProgressEvent,
  ReactionGroup,
  ReactionToggleResult,
  ReceiptTypeDto,
  ReceiptUpdate,
  RegisterRequest,
  ReplyRef,
  RoomMemberSummary,
  RoomMessageSummary,
  RoomSummary,
  RoomTimelineUpdate,
  SasUpdateEvent,
  SendQueueUpdateEvent,
  SendState,
  SlashCommand,
  SpaceChild,
  SpaceJoinRule,
  SyncStateEvent,
  TimelinePage,
  TypingUpdate,
  UploadProgress,
  VerificationRequestSummary,
};

export function login(request: LoginRequest): Promise<LoginResponse> {
  return invoke("login", { request });
}

export function register(request: RegisterRequest): Promise<LoginResponse> {
  return invoke("register", { request });
}

export function discoverHomeserver(input: string): Promise<DiscoverHomeserverResponse> {
  return invoke("discover_homeserver", { input });
}

export function startSsoLogin(homeserverUrl: string): Promise<string> {
  return invoke("start_sso_login", { homeserverUrl });
}

export function completeSsoLogin(callbackUrl: string): Promise<LoginResponse> {
  return invoke("complete_sso_login", { callbackUrl });
}

export function cancelSsoLogin(): Promise<void> {
  return invoke("cancel_sso_login");
}

export function startQrLogin(homeserverUrl: string): Promise<void> {
  return invoke("start_qr_login", { homeserverUrl });
}

export function submitQrCheckCode(code: number): Promise<void> {
  return invoke("submit_qr_check_code", { code });
}

export function cancelQrLogin(): Promise<void> {
  return invoke("cancel_qr_login");
}

export function onQrLoginProgress(
  callback: (event: QrLoginProgressEvent) => void,
): Promise<UnlistenFn> {
  return listen<QrLoginProgressEvent>("qr_login:progress", (e) => callback(e.payload));
}

export function tryRestoreSession(): Promise<LoginResponse | null> {
  return invoke("try_restore_session");
}

export function listRooms(): Promise<RoomSummary[]> {
  return invoke("list_rooms");
}

export function resolveRoomAlias(alias: string): Promise<string> {
  return invoke("resolve_room_alias", { alias });
}

/** Backs the composer's `@` mention autocomplete — see its doc comment for scope. */
export function getRoomMembers(roomId: string): Promise<RoomMemberSummary[]> {
  return invoke("get_room_members", { roomId });
}

export function onSyncState(callback: (event: SyncStateEvent) => void): Promise<UnlistenFn> {
  return listen<SyncStateEvent>("sync:state", (e) => callback(e.payload));
}

export function onRoomListUpdate(callback: (rooms: RoomSummary[]) => void): Promise<UnlistenFn> {
  return listen<RoomSummary[]>("room_list:update", (e) => callback(e.payload));
}

export function getTimelinePage(
  roomId: string,
  cursor?: string,
  limit?: number,
): Promise<TimelinePage> {
  return invoke("get_timeline_page", { roomId, cursor, limit });
}

/**
 * Queues a message and returns the SDK-generated send-queue transaction id
 * for it — key the optimistic local echo on this (not a client-generated
 * placeholder), since it's the same id the synced event's `transaction_id`
 * and `send_queue:update` events will carry, and reconciliation between the
 * three depends on all of them agreeing.
 */
export function sendMessage(
  roomId: string,
  body: string,
  formattedBody?: string | null,
  mentions?: string[] | null,
): Promise<string> {
  return invoke("send_message", {
    roomId,
    body,
    formattedBody: formattedBody ?? null,
    mentions: mentions ?? null,
  });
}

/** Runs a resolved slash command (see `parseSlashCommand` in `slashCommands.ts`). */
export function runCommand(
  roomId: string,
  command: SlashCommand,
  args: string[],
): Promise<CommandResult> {
  return invoke("run_command", { roomId, command, args });
}

export function onTimelineUpdate(
  callback: (update: RoomTimelineUpdate) => void,
): Promise<UnlistenFn> {
  return listen<RoomTimelineUpdate>("timeline:update", (e) => callback(e.payload));
}

export function editMessage(roomId: string, eventId: string, newBody: string): Promise<void> {
  return invoke("edit_message", { roomId, eventId, newBody });
}

export function redactEvent(
  roomId: string,
  eventId: string,
  reason?: string | null,
): Promise<void> {
  return invoke("redact_event", { roomId, eventId, reason: reason ?? null });
}

export function canRedact(roomId: string, targetSender: string): Promise<boolean> {
  return invoke("can_redact", { roomId, targetSender });
}

export function toggleReaction(
  roomId: string,
  targetEventId: string,
  key: string,
): Promise<ReactionToggleResult> {
  return invoke("toggle_reaction", { roomId, targetEventId, key });
}

/** Same transaction-id contract as {@link sendMessage} — see its doc comment. */
export function sendReply(roomId: string, inReplyToEventId: string, body: string): Promise<string> {
  return invoke("send_reply", { roomId, inReplyToEventId, body });
}

export function onSendQueueUpdate(
  callback: (update: SendQueueUpdateEvent) => void,
): Promise<UnlistenFn> {
  return listen<SendQueueUpdateEvent>("send_queue:update", (e) => callback(e.payload));
}

export function bootstrapCrossSigning(password?: string): Promise<void> {
  return invoke("bootstrap_cross_signing", { password });
}

export function crossSigningStatus(): Promise<CrossSigningStatusSummary> {
  return invoke("cross_signing_status");
}

export function acceptVerificationRequest(otherUserId: string, flowId: string): Promise<void> {
  return invoke("accept_verification_request", { otherUserId, flowId });
}

export function cancelVerification(otherUserId: string, flowId: string): Promise<void> {
  return invoke("cancel_verification", { otherUserId, flowId });
}

export function startSasVerification(otherUserId: string, flowId: string): Promise<void> {
  return invoke("start_sas_verification", { otherUserId, flowId });
}

export function confirmSasVerification(otherUserId: string, flowId: string): Promise<void> {
  return invoke("confirm_sas_verification", { otherUserId, flowId });
}

export function onVerificationRequest(
  callback: (request: VerificationRequestSummary) => void,
): Promise<UnlistenFn> {
  return listen<VerificationRequestSummary>("verification:request", (e) => callback(e.payload));
}

export function onSasUpdate(
  flowId: string,
  callback: (update: SasUpdateEvent) => void,
): Promise<UnlistenFn> {
  return listen<SasUpdateEvent>(`verification:sas_update:${flowId}`, (e) => callback(e.payload));
}

/**
 * `txnId` is caller-supplied (not server-generated) so it can match the ID
 * the frontend already used for its optimistic upload row before this call
 * — `upload:progress` events for this upload carry the same ID back.
 */
export function sendAttachment(
  roomId: string,
  filePath: string,
  txnId: string,
  caption?: string,
): Promise<void> {
  return invoke("send_attachment", { roomId, filePath, txnId, caption });
}

/**
 * Resolves the media attached to `eventId` in `roomId` to a local filesystem
 * path — fetching, decrypting, and caching on a miss. No handle crosses IPC:
 * the frontend just passes back the plain `(roomId, eventId)` pair it
 * already has from `RoomMessageSummary`'s `media` field ({@link MediaContent}
 * carries display metadata only). Load the returned path in an
 * `<img>`/`<video>`/`<audio>` tag via `convertFileSrc` from
 * `@tauri-apps/api/core`; never expected to be a remote URL.
 */
export function resolveMedia(roomId: string, eventId: string, thumbnail: boolean): Promise<string> {
  return invoke("resolve_media", { roomId, eventId, thumbnail });
}

export function onUploadProgress(
  callback: (progress: UploadProgress) => void,
): Promise<UnlistenFn> {
  return listen<UploadProgress>("upload:progress", (e) => callback(e.payload));
}

export function sendReadReceipt(
  roomId: string,
  eventId: string,
  isPrivate: boolean,
): Promise<void> {
  return invoke("send_read_receipt", { roomId, eventId, private: isPrivate });
}

export function sendTyping(roomId: string, typing: boolean): Promise<void> {
  return invoke("send_typing", { roomId, typing });
}

export function markRoomRead(roomId: string): Promise<void> {
  return invoke("mark_room_read", { roomId });
}

export function onReceiptsUpdate(callback: (update: ReceiptUpdate) => void): Promise<UnlistenFn> {
  return listen<ReceiptUpdate>("receipts:update", (e) => callback(e.payload));
}

export function onTypingUpdate(callback: (update: TypingUpdate) => void): Promise<UnlistenFn> {
  return listen<TypingUpdate>("typing:update", (e) => callback(e.payload));
}

export function setPresence(presence: PresenceStateDto, statusMsg?: string): Promise<void> {
  return invoke("set_presence", { presence, statusMsg });
}

export function getPresence(userId: string): Promise<PresenceUpdate | null> {
  return invoke("get_presence", { userId });
}

export function onPresenceUpdate(callback: (update: PresenceUpdate) => void): Promise<UnlistenFn> {
  return listen<PresenceUpdate>("presence:update", (e) => callback(e.payload));
}

export function setRoomFavourite(roomId: string, favourite: boolean): Promise<void> {
  return invoke("set_room_favourite", { roomId, favourite });
}

export function setRoomLowPriority(roomId: string, lowPriority: boolean): Promise<void> {
  return invoke("set_room_low_priority", { roomId, lowPriority });
}

export function setRoomMuted(roomId: string, muted: boolean): Promise<void> {
  return invoke("set_room_muted", { roomId, muted });
}

export function setRoomMarkedUnread(roomId: string, unread: boolean): Promise<void> {
  return invoke("set_room_marked_unread", { roomId, unread });
}

/** `order` is the fractional-index midpoint the caller computes between the room's two new neighbours in its section — see `RoomList.tsx`'s drag-reorder handler. */
export function setRoomManualOrder(roomId: string, order: number): Promise<void> {
  return invoke("set_room_manual_order", { roomId, order });
}

export function listSpaceChildren(spaceId: string): Promise<SpaceChild[]> {
  return invoke("list_space_children", { spaceId });
}

export function joinRoom(roomIdOrAlias: string): Promise<void> {
  return invoke("join_room", { roomIdOrAlias });
}

export function knockRoom(roomIdOrAlias: string, reason?: string): Promise<void> {
  return invoke("knock_room", { roomIdOrAlias, reason });
}
