import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";
import type { CrossSigningStatusSummary } from "@bindings/CrossSigningStatusSummary";
import type { DiscoverHomeserverResponse } from "@bindings/DiscoverHomeserverResponse";
import type { EmojiPair } from "@bindings/EmojiPair";
import type { EventReceipt } from "@bindings/EventReceipt";
import type { LoginRequest } from "@bindings/LoginRequest";
import type { LoginResponse } from "@bindings/LoginResponse";
import type { PresenceStateDto } from "@bindings/PresenceStateDto";
import type { PresenceUpdate } from "@bindings/PresenceUpdate";
import type { QrLoginProgressEvent } from "@bindings/QrLoginProgressEvent";
import type { ReceiptTypeDto } from "@bindings/ReceiptTypeDto";
import type { ReceiptUpdate } from "@bindings/ReceiptUpdate";
import type { RegisterRequest } from "@bindings/RegisterRequest";
import type { RoomMessageSummary } from "@bindings/RoomMessageSummary";
import type { RoomSummary } from "@bindings/RoomSummary";
import type { RoomTimelineUpdate } from "@bindings/RoomTimelineUpdate";
import type { SasUpdateEvent } from "@bindings/SasUpdateEvent";
import type { SyncStateEvent } from "@bindings/SyncStateEvent";
import type { TimelinePage } from "@bindings/TimelinePage";
import type { TypingUpdate } from "@bindings/TypingUpdate";
import type { VerificationRequestSummary } from "@bindings/VerificationRequestSummary";

/**
 * IPC types are generated from the Rust structs by ts-rs — see
 * `src-tauri/src/bindings/`, regenerated by `cargo test --lib` and drift-checked in CI
 * (any uncommitted change fails the build). They're re-exported here so the rest of the
 * frontend imports the IPC types and their `invoke`/`listen` wrappers from one place;
 * do not redefine them by hand.
 */
export type {
  CrossSigningStatusSummary,
  DiscoverHomeserverResponse,
  EmojiPair,
  EventReceipt,
  LoginRequest,
  LoginResponse,
  PresenceStateDto,
  PresenceUpdate,
  QrLoginProgressEvent,
  ReceiptTypeDto,
  ReceiptUpdate,
  RegisterRequest,
  RoomMessageSummary,
  RoomSummary,
  RoomTimelineUpdate,
  SasUpdateEvent,
  SyncStateEvent,
  TimelinePage,
  TypingUpdate,
  VerificationRequestSummary,
};

export function login(request: LoginRequest): Promise<LoginResponse> {
  return invoke("login", { request });
}

export function register(request: RegisterRequest): Promise<LoginResponse> {
  return invoke("register", { request });
}

export function discoverHomeserver(input: string): Promise<DiscoverHomeserverResponse> {
  return invoke("discover_homeserver", { input });
}

export function startSsoLogin(homeserverUrl: string): Promise<string> {
  return invoke("start_sso_login", { homeserverUrl });
}

export function completeSsoLogin(callbackUrl: string): Promise<LoginResponse> {
  return invoke("complete_sso_login", { callbackUrl });
}

export function cancelSsoLogin(): Promise<void> {
  return invoke("cancel_sso_login");
}

export function startQrLogin(homeserverUrl: string): Promise<void> {
  return invoke("start_qr_login", { homeserverUrl });
}

export function submitQrCheckCode(code: number): Promise<void> {
  return invoke("submit_qr_check_code", { code });
}

export function cancelQrLogin(): Promise<void> {
  return invoke("cancel_qr_login");
}

export function onQrLoginProgress(
  callback: (event: QrLoginProgressEvent) => void,
): Promise<UnlistenFn> {
  return listen<QrLoginProgressEvent>("qr_login:progress", (e) => callback(e.payload));
}

export function tryRestoreSession(): Promise<LoginResponse | null> {
  return invoke("try_restore_session");
}

export function listRooms(): Promise<RoomSummary[]> {
  return invoke("list_rooms");
}

export function resolveRoomAlias(alias: string): Promise<string> {
  return invoke("resolve_room_alias", { alias });
}

export function onSyncState(callback: (event: SyncStateEvent) => void): Promise<UnlistenFn> {
  return listen<SyncStateEvent>("sync:state", (e) => callback(e.payload));
}

export function onRoomListUpdate(callback: (rooms: RoomSummary[]) => void): Promise<UnlistenFn> {
  return listen<RoomSummary[]>("room_list:update", (e) => callback(e.payload));
}

export function getTimelinePage(
  roomId: string,
  cursor?: string,
  limit?: number,
): Promise<TimelinePage> {
  return invoke("get_timeline_page", { roomId, cursor, limit });
}

export function sendMessage(roomId: string, body: string): Promise<void> {
  return invoke("send_message", { roomId, body });
}

export function onTimelineUpdate(
  callback: (update: RoomTimelineUpdate) => void,
): Promise<UnlistenFn> {
  return listen<RoomTimelineUpdate>("timeline:update", (e) => callback(e.payload));
}

export function bootstrapCrossSigning(password?: string): Promise<void> {
  return invoke("bootstrap_cross_signing", { password });
}

export function crossSigningStatus(): Promise<CrossSigningStatusSummary> {
  return invoke("cross_signing_status");
}

export function acceptVerificationRequest(otherUserId: string, flowId: string): Promise<void> {
  return invoke("accept_verification_request", { otherUserId, flowId });
}

export function cancelVerification(otherUserId: string, flowId: string): Promise<void> {
  return invoke("cancel_verification", { otherUserId, flowId });
}

export function startSasVerification(otherUserId: string, flowId: string): Promise<void> {
  return invoke("start_sas_verification", { otherUserId, flowId });
}

export function confirmSasVerification(otherUserId: string, flowId: string): Promise<void> {
  return invoke("confirm_sas_verification", { otherUserId, flowId });
}

export function onVerificationRequest(
  callback: (request: VerificationRequestSummary) => void,
): Promise<UnlistenFn> {
  return listen<VerificationRequestSummary>("verification:request", (e) => callback(e.payload));
}

export function onSasUpdate(
  flowId: string,
  callback: (update: SasUpdateEvent) => void,
): Promise<UnlistenFn> {
  return listen<SasUpdateEvent>(`verification:sas_update:${flowId}`, (e) => callback(e.payload));
}

export function sendReadReceipt(
  roomId: string,
  eventId: string,
  isPrivate: boolean,
): Promise<void> {
  return invoke("send_read_receipt", { roomId, eventId, private: isPrivate });
}

export function sendTyping(roomId: string, typing: boolean): Promise<void> {
  return invoke("send_typing", { roomId, typing });
}

export function markRoomRead(roomId: string): Promise<void> {
  return invoke("mark_room_read", { roomId });
}

export function onReceiptsUpdate(callback: (update: ReceiptUpdate) => void): Promise<UnlistenFn> {
  return listen<ReceiptUpdate>("receipts:update", (e) => callback(e.payload));
}

export function onTypingUpdate(callback: (update: TypingUpdate) => void): Promise<UnlistenFn> {
  return listen<TypingUpdate>("typing:update", (e) => callback(e.payload));
}

export function setPresence(presence: PresenceStateDto, statusMsg?: string): Promise<void> {
  return invoke("set_presence", { presence, statusMsg });
}

export function getPresence(userId: string): Promise<PresenceUpdate | null> {
  return invoke("get_presence", { userId });
}

export function onPresenceUpdate(callback: (update: PresenceUpdate) => void): Promise<UnlistenFn> {
  return listen<PresenceUpdate>("presence:update", (e) => callback(e.payload));
}
