// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpaceBadgeState } from "./SpaceBadgeState";

/**
 * Total unread state across every room, derived from the same
 * [`super::rooms::has_unread`] signal `RoomSummary`/the room list already
 * use — never re-derived from a naive per-room message count, so a muted
 * room with only ambient unread never inflates the badge, while an explicit
 * mark-unread or a real mention (which still carries a nonzero
 * `unread_count` even in a muted room) always does.
 */
export type BadgeState = { 
/**
 * Number of rooms with `has_unread() == true`.
 */
total_unread: number, 
/**
 * Sum of `unread_count` (mention/highlight notifications) across every
 * room — a finer-grained signal than `total_unread` for surfacing "you
 * were mentioned N times" distinctly from ambient unread rooms.
 */
total_highlight: number, 
/**
 * Rollups keyed by space room id. Each value sums descendant rooms via
 * `RoomSummary.parent_space_ids`, so rooms nested under a sub-space
 * also count for every ancestor space currently present in the room
 * snapshot.
 */
spaces: { [key in string]: SpaceBadgeState }, };
