// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookmarkEntry = { room_id: string, event_id: string, 
/**
 * Milliseconds since the Unix epoch, when this bookmark was created —
 * drives the Saved Messages list's newest-saved-first ordering. Not the
 * same as the message's own `timestamp_ms` (when it was *sent*).
 */
saved_at_ms: number, sender: string, sender_display_name: string | null, 
/**
 * Truncated preview of the message body at save time — see the module
 * doc for why this is snapshotted rather than re-resolved live.
 */
body_preview: string, timestamp_ms: number, };
