// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of `run_command`, so the composer can show inline feedback
 * (success / permission-denied / bad-args) instead of a bare error string.
 */
export type CommandResult = { "status": "success" } | { "status": "permission_denied", message: string, } | { "status": "bad_args", message: string, };
