// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrossSigningStatusSummary = { has_master_key: boolean, has_self_signing_key: boolean, has_user_signing_key: boolean, };
