// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceSummary = { device_id: string, display_name: string | null, last_seen_ip: string | null, 
/**
 * Milliseconds since the Unix epoch — some homeservers don't populate
 * this (see Spec 08's "Risks & open questions"), so the UI must tolerate
 * `None`.
 */
last_seen_ts: number | null, is_current: boolean, 
/**
 * Cross-signing *or* locally trusted — matrix-rust-sdk's
 * `Device::is_verified()`, the same signal Element's client uses for a
 * device's trust badge.
 */
is_verified: boolean, };
