// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Do Not Disturb state: whether it's on, and (if timed) when it ends.
 */
export type DndState = { enabled: boolean, 
/**
 * Epoch ms the DND period ends, or `None` for indefinite ("until I turn
 * it off"). Ignored when `enabled` is `false`.
 */
until: number | null, };
