// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DND state exposed over IPC/events, plus the Rust-owned transition revision
 * used to reject a Settings command that was initiated before a newer tray
 * action. The revision is process-local; no command survives an app restart.
 */
export type DndSnapshot = { enabled: boolean, until: number | null, revision: number, };
