// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a message's edit history — either the original event, or one
 * of its `m.replace` edits, in chronological (oldest-first) order.
 */
export type EditHistoryEntry = { event_id: string, body: string, formatted_body: string | null, sender: string, origin_server_ts: number, };
