// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReceiptTypeDto } from "./ReceiptTypeDto";

/**
 * One user's receipt on one event, flattened out of the nested
 * `ReceiptEventContent` map for the frontend. Only `Read`/`ReadPrivate`
 * receipts are surfaced here — `FullyRead` is a private per-user marker, not
 * something rendered as another user's avatar.
 */
export type EventReceipt = { event_id: string, user_id: string, receipt_type: ReceiptTypeDto, ts_ms: number, };
