// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, authoritative flag keys. Serialized `snake_case` — the serialized
 * string is the wire/store key and must never change once shipped (renaming a
 * variant silently orphans any persisted override / remote-config entry).
 *
 * Exported to the frontend as a union type; a JS catalog missing or misspelling
 * a key fails `tsc`.
 */
export type FeatureFlagKey = "canary" | "room_invites" | "rich_message_rendering" | "mobile_chat_redesign" | "focus_mode" | "link_previews" | "room_alias_management" | "room_list_unread_filter" | "message_action_parity" | "media_send_polish" | "room_list_message_preview" | "space_rail_management" | "message_pinning" | "presence_privacy_controls" | "bookmarks" | "room_list_sort" | "room_list_typing_indicator";
