// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureFlagKey } from "./FeatureFlagKey";

/**
 * Catalog metadata for one flag, exported to the frontend so the Labs panel
 * can render the list without a second source of truth.
 */
export type FeatureFlagCatalogEntry = { key: FeatureFlagKey, default: boolean, description: string, owner: string, };
