// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Matrix room hero exposed for Spec 53's group-DM composite avatar and
 * aggregate presence ring. `Room::heroes()` already excludes the signed-in
 * user and follows the homeserver/SDK's stable room-summary ordering.
 */
export type GroupDmAvatarMember = { user_id: string, display_name: string | null, avatar_url: string | null, };
