// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of a successful [`join_room`] call. `is_space` lets a caller
 * that doesn't already know the room's type (e.g. the create/join dialog,
 * given only a user-typed address) tell a space apart from a regular room
 * without a separate lookup.
 */
export type JoinedRoom = { room_id: string, is_space: boolean, };
