// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of [`load_timeline_around_event`] — richer than a plain `found`
 * bool so the frontend can tell *how* the event was found. Review fix: the
 * common case (the event is within the room's already-cached live
 * timeline, or reachable by the bounded `paginate_backwards` scan below)
 * never touches [`load_focused_event_timeline`]'s server-side `/context`
 * fallback at all — no focused-view swap happens, so the room's cached
 * `Timeline` is still the live one. A plain `bool` return gave the
 * frontend no way to distinguish that from the rarer case where the
 * fallback *did* run and did swap the cache to a focused view, which is
 * the only case where a later "Jump to Present" needs to force the room
 * back to live — `ChatShell` was otherwise treating every successful jump
 * as if it might have focused the view, forcing an unnecessary re-fetch
 * (and the scroll-animation disruption that comes with replacing
 * `messages`) for the much more common non-focusing case.
 */
export type JumpToEventResult = { found: boolean, installed_focused_view: boolean, };
