// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compact last-message preview for a room-list row (Spec 54): the
 * sender's user id (always present) and resolved display name (best
 * effort), plus a truncated text snippet. `None` on [`RoomSummary`] when the
 * room has no known latest event yet, the latest event isn't a plain
 * (decrypted, non-redacted) `m.room.message`, or it's a pending invite —
 * callers fall back to showing just the room name, same as before this
 * field existed.
 */
export type LastMessagePreview = { sender_id: string, sender_display_name: string | null, 
/**
 * Already truncated to [`LAST_MESSAGE_PREVIEW_MAX_CHARS`] chars (with a
 * trailing `…` when truncated) — the frontend still applies CSS
 * `truncate` for narrow layouts, but doesn't need to bound the length
 * itself.
 */
text: string, };
