// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginIdentityProvider } from "./LoginIdentityProvider";

export type LoginFlowSummary = { password: boolean, token: boolean, sso: boolean, identity_providers: Array<LoginIdentityProvider>, delegated_auth: boolean, account_management_url: string | null, };
