// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tagged union carrying msgtype + media metadata for a message event —
 * generalizes the old flat `body: String` (kept below on
 * [`RoomMessageSummary`] for text-preview/room-list use, additively) so the
 * timeline can render non-text msgtypes.
 *
 * Media variants carry a [`MediaHandle`] (opaque, serialized
 * `MediaSource`), never the raw `EncryptedFile` — that would leak the AES
 * key across IPC. `resolve_media` turns a handle into a local file path.
 */
export type MessageContent = { "type": "Text", body: string, } | { "type": "Image", body: string, source: string, mime: string | null, size: number | null, width: number | null, height: number | null, thumbnail: string | null, blurhash: string | null, } | { "type": "Video", body: string, source: string, mime: string | null, size: number | null, width: number | null, height: number | null, duration_ms: number | null, thumbnail: string | null, } | { "type": "Audio", body: string, source: string, mime: string | null, size: number | null, duration_ms: number | null, } | { "type": "File", body: string, source: string, mime: string | null, size: number | null, };
