// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal room identity returned for the mutual-rooms section of a profile
 * card. Notification counts, tags, and message previews from `RoomSummary`
 * are deliberately excluded because they are unrelated private room-list
 * state.
 */
export type MutualRoomSummary = { room_id: string, name: string | null, avatar_url: string | null, avatar_path: string | null, is_direct: boolean, is_space: boolean, };
