// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomNotificationModeKind } from "./RoomNotificationModeKind";

export type NotificationSettingsSummary = { default_mode: RoomNotificationModeKind, keywords: Array<string>, global_mute: boolean, sound_enabled: boolean, };
