// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceStateDto } from "./PresenceStateDto";

/**
 * The signed-in user's own profile + presence, for the room-list header
 * (and a future account switcher). Read-only — editing your own profile is
 * a Spec 01 non-goal.
 */
export type OwnProfile = { user_id: string, display_name: string | null, avatar_url: string | null, avatar_path: string | null, presence: PresenceStateDto, };
