// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single pinned message resolved for display in the pinned-messages
 * panel (Spec day-2/04). Deliberately its own small DTO rather than reusing
 * `timeline::RoomMessageSummary`: a pinned event may be arbitrarily old and
 * outside any currently-loaded timeline window, may be undecrypted, or may
 * already be redacted (unpinning doesn't automatically follow a redaction),
 * so this only carries the handful of fields the panel actually renders
 * plus enough state to render each of those cases distinctly.
 */
export type PinnedMessageSummary = { event_id: string, sender: string, sender_display_name: string | null, 
/**
 * Message body, or `""` if the event is redacted, undecrypted, or
 * isn't a `m.room.message` at all (e.g. someone pinned a state event —
 * Matrix's spec allows pinning any event, not just messages). Check
 * `is_redacted`/`is_undecrypted` before treating an empty body as "no
 * content".
 */
preview: string, timestamp_ms: number, is_redacted: boolean, is_undecrypted: boolean, };
