// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PollAnswerSummary = { id: string, text: string, votes: number, selected_by_me: boolean, };
