// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollAnswerSummary } from "./PollAnswerSummary";
import type { PollKindSummary } from "./PollKindSummary";

export type PollSummary = { question: string, kind: PollKindSummary, max_selections: number, answers: Array<PollAnswerSummary>, ended: boolean, edited: boolean, };
