// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PowerLevelThresholds = { invite: number, kick: number, ban: number, redact: number, events_default: number, state_default: number, users_default: number, };
