// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceStateDto } from "./PresenceStateDto";

/**
 * Pushed to the frontend whenever an `m.presence` event arrives for another
 * user, and returned (wrapped in `Option`) by `get_presence`'s best-effort
 * lookup.
 */
export type PresenceUpdate = { user_id: string, presence: PresenceStateDto, status_msg: string | null, last_active_ago_ms: number | null, };
