// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors ruma's `PresenceState` for the frontend. `PresenceState` itself has
 * a hidden `_Custom` variant for forward-compat. Spec 53 recognizes the
 * de-facto `dnd` / `busy` values as one visual state; every other custom
 * value remains fail-closed as `Offline`.
 */
export type PresenceStateDto = "online" | "unavailable" | "dnd" | "offline";
