// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mirrors ruma's `PresenceState` for the frontend. `PresenceState` itself has
 * a hidden `_Custom` variant for forward-compat, which isn't meaningful to
 * surface as a DTO — anything that isn't one of the three known states is
 * mapped to `Offline` (see `presence_state_to_dto`).
 */
export type PresenceStateDto = "online" | "unavailable" | "offline";
