// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client-local privacy preferences. `idle_timeout_minutes: None` means
 * auto-idle is disabled; the frontend idle timer (Spec 40 item 4) reads
 * this to know whether/when to flip presence to `unavailable`.
 */
export type PrivacySettings = { 
/**
 * When `true`, don't send `m.read`/`m.read.private` receipts (the
 * `m.fully_read` marker — a private, per-user pointer never shown to
 * others — is still sent so local "jump to unread" tracking keeps
 * working).
 */
hide_read_receipts: boolean, 
/**
 * When `true`, don't send `m.typing` notices from the composer.
 */
hide_typing: boolean, 
/**
 * "Appear offline": force presence to `offline` regardless of what the
 * sync loop or auto-idle timer would otherwise set.
 */
appear_offline: boolean, 
/**
 * Minutes of inactivity before the frontend idle timer sets presence to
 * `unavailable`. `None` disables auto-idle.
 */
idle_timeout_minutes: number | null, };
