// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProfileSummary = { user_id: string, display_name: string | null, avatar_url: string | null, 
/**
 * Whether this session was established via OAuth 2.0/OIDC (QR login;
 * see `auth::start_qr_login`) rather than the classic `matrix_auth()`
 * login API (password or SSO). `change_password`/`deactivate_account`
 * only ever retry UIA with `AuthData::Password`, which an OIDC-managed
 * account's homeserver has no obligation to accept (account
 * management for those is typically delegated to the OIDC provider
 * instead) — the frontend uses this to hide actions that can't
 * succeed rather than let them fail confusingly.
 */
uses_oauth: boolean, };
