// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { PublicRoomSummary } from "./PublicRoomSummary";

export type PublicRoomPage = { rooms: Array<PublicRoomSummary>, next_batch: string | null, total_room_count_estimate: number | null, };
