// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicRoomSummary = { room_id: string, name: string | null, topic: string | null, canonical_alias: string | null, avatar_url: string | null, joined_members: number, };
