// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PusherKind } from "./PusherKind";

export type PushStatus = { transport: PusherKind, registered: boolean, endpoint_present: boolean, last_error: string | null, };
