// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which transport (if any) currently backs push delivery — the ts-rs IPC
 * enum the frontend uses to render transport-specific settings UI (e.g. the
 * Android distributor picker).
 */
export type PusherKind = "unified_push" | "fcm" | "apns" | "none";
