// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PusherKind } from "./PusherKind";

export type PushStatus = { transport: PusherKind, registered: boolean, endpoint_present: boolean, last_error: string | null, 
/**
 * Whether *some* platform transport exists on this device at all
 * (`active_transport(&app).is_some()`), independent of whether it's
 * currently registered. Distinguishes "this is desktop, push will never
 * be available" from "this is mobile, but nothing has registered yet" —
 * before the first `register_push` call, `transport` reads `none` in
 * both cases, and the settings panel needs to tell them apart to know
 * whether to offer a "turn on" button at all.
 */
available: boolean, };
