// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PusherKind } from "./PusherKind";

/**
 * ts-rs mirror of one endpoint's registration state — the `register_push`/
 * `unregister_push` command return value. See [`PushStatus`] for the
 * `push:status` event payload, which additionally carries `last_error` for
 * the settings-panel diagnostics this spec's "New commands + events" calls
 * for.
 */
export type PushRegistration = { transport: PusherKind, registered: boolean, endpoint_present: boolean, };
