// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginResponse } from "./LoginResponse";

export type QrLoginProgressEvent = { "state": "qr_ready", qr_code_bytes: Array<number>, } | { "state": "waiting_for_check_code" } | { "state": "waiting_for_approval" } | { "state": "syncing_secrets" } | { "state": "done", session: LoginResponse, } | { "state": "cancelled", reason: string, } | { "state": "error", message: string, };
