// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `toggle_reaction`, so the frontend can optimistically flip
 * local state without waiting for a `timeline:update` round-trip.
 */
export type ReactionToggleResult = { "action": "added" } | { "action": "removed" };
