// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reactor on a given reaction `key` for a target event — who reacted
 * and when.
 */
export type ReactionDetail = { sender: string, origin_server_ts: number, };
