// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventReceipt } from "./EventReceipt";

/**
 * Pushed to the frontend whenever a sync response carries `m.receipt`
 * ephemeral events for a room.
 */
export type ReceiptUpdate = { room_id: string, receipts: Array<EventReceipt>, };
