// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A device's key-backup/secret-storage ("4S") recovery state, exposed to
 * the frontend so it knows whether to prompt for a recovery key.
 * `incomplete` is the state this feature exists for: secrets/backup exist
 * on the server (some other session set them up), but this device — e.g. a
 * `charm-web-server` session that just lost its in-memory crypto store to a
 * restart, see `crates/charm-web-server/src/persistence.rs`'s module doc
 * comment — doesn't have them locally, so previously-decrypted room
 * history is unreadable until the user enters their recovery key.
 */
export type RecoveryStatusSummary = "unknown" | "enabled" | "disabled" | "incomplete";
