// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegistrationAuthResponse = { "kind": "accept_terms" } | { "kind": "complete_dummy" } | { "kind": "complete_email", token: string | null, } | { "kind": "acknowledge_fallback", stage: string, };
