// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginResponse } from "./LoginResponse";
import type { RegistrationFlow } from "./RegistrationFlow";
import type { RegistrationPolicy } from "./RegistrationPolicy";

export type RegistrationStep = { "state": "challenge", attempt_id: string, session: string, completed: Array<string>, flows: Array<RegistrationFlow>, next_stage: string, fallback_url: string, policies: Array<RegistrationPolicy>, } | { "state": "complete", session: LoginResponse, };
