// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReplyRef = { event_id: string, sender: string, 
/**
 * Resolved from the replied-to event's own `sender_profile()` — `None`
 * if that event isn't loaded/resolved yet, same caveat as `preview`.
 */
sender_display_name: string | null, preview: string, };
