// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomNotificationModeKind = "all_messages" | "mentions_and_keywords_only" | "mute";
