// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastMessagePreview } from "./LastMessagePreview";
import type { RoomMembershipKind } from "./RoomMembershipKind";
import type { RoomNotificationModeKind } from "./RoomNotificationModeKind";

/**
 * Flat room summary for the room list. No message preview yet — that needs
 * the timeline/event-cache API, which is Phase 1 timeline-rendering scope,
 * not this first sync-wiring cut.
 *
 * `has_unread` is the single authoritative "needs attention" signal (see
 * [`has_unread`]) — computed once here, in [`snapshot_rooms`]; every UI
 * unread indicator reads this field rather than re-deriving it from
 * `unread_count`/`unread_messages`/`is_marked_unread` itself.
 *
 * `list_rooms`/`room_list:update` pre-sort pending invites first, followed by
 * joined rooms ordered by (section, `manual_order`, name) in
 * [`snapshot_rooms`] — the frontend performs no sorting.
 */
export type RoomSummary = { room_id: string, name: string | null, unread_count: number, 
/**
 * `room.num_unread_messages()` — ambient unread, distinct from
 * `unread_count` (notifications/mentions).
 */
unread_messages: number, 
/**
 * The MSC2867 `m.marked_unread` flag (`room.is_marked_unread()`).
 */
is_marked_unread: boolean, 
/**
 * True when the user-defined-or-default notification mode for this
 * room is `Mute`. Kept alongside `notification_mode` below for the
 * existing `has_unread`/room-list consumers that only ever needed the
 * muted/not-muted distinction.
 */
is_muted: boolean, 
/**
 * The room's effective notification mode (user-defined override, or the
 * account default if none is set) — distinguishes `AllMessages` from
 * `MentionsAndKeywordsOnly`, which `is_muted` alone can't (both read as
 * "not muted" there). `None` only if the client couldn't resolve a mode
 * at all (e.g. room not yet fully synced). The settings Notifications
 * panel's per-room picker reads this rather than reconstructing a mode
 * from `is_muted`.
 */
notification_mode: RoomNotificationModeKind | null, 
/**
 * `m.favourite` tag present.
 */
is_favourite: boolean, 
/**
 * `m.lowpriority` tag present.
 */
is_low_priority: boolean, 
/**
 * `TagInfo.order` for whichever tag currently governs this room's
 * section — see [`order_tag_name`]. `None` sorts last within its
 * section.
 */
manual_order: number | null, 
/**
 * `room.room_type() == Some(RoomType::Space)`.
 */
is_space: boolean, 
/**
 * Space room ids whose `m.space.child` state references this room.
 */
parent_space_ids: Array<string>, 
/**
 * `room.is_direct()` (DM grouping).
 */
is_direct: boolean, 
/**
 * The single "does this room need attention" signal — see
 * [`has_unread`]. Every unread indicator in the UI reads this, not the
 * raw counts above.
 */
has_unread: boolean, 
/**
 * The room's own avatar mxc, when `m.room.avatar` is set — otherwise,
 * for an unnamed direct room, the single peer's avatar (from
 * `Room::heroes()`). `None` means render the initials fallback; see
 * [`resolve_room_identity`].
 */
avatar_url: string | null, 
/**
 * `avatar_url` resolved to a local thumbnail path via Spec 02's media
 * cache, or `None` if unresolved (no cache yet, no avatar, or the fetch
 * failed) — the frontend falls back to initials in that case.
 */
avatar_path: string | null, 
/**
 * For a direct room with exactly one other member, that member's user
 * id — lets the frontend key a presence lookup (`usePresence`) off the
 * DM peer rather than the room. `None` for group rooms and for direct
 * rooms matrix-rust-sdk can't resolve a single hero for (e.g. the peer
 * hasn't been synced yet).
 */
dm_peer_user_id: string | null, 
/**
 * Whether this is a normal joined room or a pending invitation. Left,
 * knocked, and banned rooms are deliberately excluded from snapshots.
 */
membership: RoomMembershipKind, 
/**
 * The user who sent a pending invitation. `None` for joined rooms or
 * when a malformed/incomplete invite omitted its membership event.
 */
inviter_user_id: string | null, inviter_display_name: string | null, 
/**
 * Spec 54 room-list row enrichment: a compact sender + text snippet for
 * the room's most recent message, or `None` when none is available yet
 * — see [`last_message_preview`].
 */
last_message_preview: LastMessagePreview | null, 
/**
 * Spec 54 activity sort: the latest event's timestamp (remote or a
 * still-sending local echo), milliseconds since the Unix epoch. `None`
 * when activity sort is off or no latest event has been computed yet —
 * the frontend falls back to the default section/manual-order/name
 * ordering in that case. See [`last_activity_ts`].
 */
last_activity_ts: number | null, };
