// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MembershipKind } from "./MembershipKind";

/**
 * A room member as offered by the `@` mention autocomplete and the Spec 07
 * member-management panel — one shared shape/mapping ([`member_to_summary`])
 * for both, rather than two near-identical member DTOs.
 */
export type RoomMemberSummary = { user_id: string, display_name: string | null, avatar_url: string | null, power_level: number, membership: MembershipKind, };
