// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A room member as offered by the `@` mention autocomplete. Deliberately
 * thin — just enough to filter and render a suggestion row and build a
 * mention pill.
 */
export type RoomMemberSummary = { user_id: string, display_name: string | null, };
