// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flat room summary for the room list. No message preview yet — that needs
 * the timeline/event-cache API, which is Phase 1 timeline-rendering scope,
 * not this first sync-wiring cut.
 */
export type RoomSummary = { room_id: string, name: string | null, unread_count: number, };
