// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomPermissions = { set_name: boolean, set_topic: boolean, set_avatar: boolean, set_join_rules: boolean, set_history_visibility: boolean, set_encryption: boolean, set_power_levels: boolean, invite: boolean, kick: boolean, ban: boolean, 
/**
 * Gates both the canonical-alias selector and add/remove-alias controls
 * (Spec 32) — Matrix has no separate power-level requirement for
 * publishing/unpublishing a room-directory alias, only for the
 * `m.room.canonical_alias` *state event* itself, so this single check
 * covers the whole alias-management surface per the spec's power-level
 * gating requirement.
 */
set_canonical_alias: boolean, 
/**
 * Gates the "Pin"/"Unpin" entry in `MessageActions` and any other
 * pin/unpin affordance (Spec day-2/04) — power level required to send
 * `m.room.pinned_events`, same pattern as every other `set_*` field
 * above.
 */
set_pinned_events: boolean, 
/**
 * Gates `SpaceRail`'s "Add existing…", "Mark/Unmark as suggested", and
 * "Remove from space" actions (Spec 63) — power level required to send
 * `m.space.child` in *this* room. "Add existing" checks it against the
 * target space being added to; "Suggested"/"Remove" check it against
 * the child's *parent* space (a second, separately-fetched
 * `RoomDetails`), since that's whose `m.space.child` edge is mutated.
 */
set_space_child: boolean, };
