// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomPermissions = { set_name: boolean, set_topic: boolean, set_avatar: boolean, set_join_rules: boolean, set_history_visibility: boolean, set_encryption: boolean, set_power_levels: boolean, invite: boolean, kick: boolean, ban: boolean, };
