// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomKeyImportSummary = {
  completed: boolean;
  imported_count: number;
  total_count: number;
};
