// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaContent } from "./MediaContent";
import type { ReactionGroup } from "./ReactionGroup";
import type { ReplyRef } from "./ReplyRef";
import type { SendState } from "./SendState";

export type RoomMessageSummary = { event_id: string, sender: string, 
/**
 * Resolved from `EventTimelineItem::sender_profile()` — already
 * fetched and kept live by `matrix-sdk-ui`'s `Timeline` itself (it
 * re-resolves and re-diffs on membership changes), so this never costs
 * its own `get_member` round-trip. `None` (fall back to `sender`, the
 * MXID) when the profile hasn't resolved yet or the member has no
 * display name set.
 */
sender_display_name: string | null, 
/**
 * The sender's avatar mxc, if set — carried alongside the resolved
 * `sender_avatar_path` so the frontend can cache-key on the mxc
 * independently of local path resolution.
 */
sender_avatar_url: string | null, 
/**
 * `sender_avatar_url` resolved to a local thumbnail path via Spec 02's
 * media cache, or `None` if unresolved — the frontend falls back to an
 * initials avatar in that case.
 */
sender_avatar_path: string | null, 
/**
 * Text-preview/room-list use — kept for backwards compatibility
 * alongside `content`, which carries the full tagged-union payload.
 */
body: string, 
/**
 * `org.matrix.custom.html` formatted body, when the message (or its
 * latest edit) has one — see `formatted_html_body` in this module.
 * `None` for plain-text messages. Rendered only after re-sanitizing
 * against the Matrix-permitted allowlist (`composerSanitize.ts`); never
 * trust this as pre-sanitized just because it came from the SDK.
 */
formatted_body: string | null, timestamp_ms: number, edited: boolean, redacted: boolean, reactions: Array<ReactionGroup>, in_reply_to: ReplyRef | null, transaction_id: string | null, send_state: SendState, 
/**
 * `None` for text/notice/emote messages; `Some` for image/video/audio/file
 * msgtypes. See [`MediaContent`] and `resolve_media` (in `mod.rs`) for
 * how the frontend turns this into an actual displayable/downloadable
 * local path.
 */
media: MediaContent | null, };
