// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryVisibilityKind } from "./HistoryVisibilityKind";
import type { JoinRuleKind } from "./JoinRuleKind";
import type { PowerLevelThresholds } from "./PowerLevelThresholds";
import type { RoomPermissions } from "./RoomPermissions";

export type RoomDetails = { room_id: string, name: string | null, topic: string | null, avatar_url: string | null, is_encrypted: boolean, join_rule: JoinRuleKind, history_visibility: HistoryVisibilityKind, member_count: number, my_power_level: number, power_levels: PowerLevelThresholds, can: RoomPermissions, };
