// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoomPermissions = { set_name: boolean, set_topic: boolean, set_avatar: boolean, set_join_rules: boolean, set_history_visibility: boolean, set_encryption: boolean, set_power_levels: boolean, invite: boolean, kick: boolean, ban: boolean, 
/**
 * Gates both the canonical-alias selector and add/remove-alias controls
 * (Spec 32) — Matrix has no separate power-level requirement for
 * publishing/unpublishing a room-directory alias, only for the
 * `m.room.canonical_alias` *state event* itself, so this single check
 * covers the whole alias-management surface per the spec's power-level
 * gating requirement.
 */
set_canonical_alias: boolean, };
