// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMessageSummary } from "./RoomMessageSummary";

/**
 * Pushed to the frontend whenever a sync response brings new timeline events
 * for a room the client is joined to — so a room's message list can update
 * live without the frontend re-fetching a `TimelinePage` after every sync.
 */
export type RoomTimelineUpdate = { room_id: string, messages: Array<RoomMessageSummary>, };
