// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReactionGroup } from "./ReactionGroup";
import type { ReplyRef } from "./ReplyRef";
import type { SendState } from "./SendState";

export type RoomMessageSummary = { event_id: string, sender: string, body: string, 
/**
 * Reserved: always `None` until the formatted-body/rich-text composition spec lands.
 */
formatted_body: string | null, timestamp_ms: number, edited: boolean, redacted: boolean, reactions: Array<ReactionGroup>, in_reply_to: ReplyRef | null, transaction_id: string | null, send_state: SendState, };
