// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaContent } from "./MediaContent";
import type { ReactionGroup } from "./ReactionGroup";
import type { ReplyRef } from "./ReplyRef";
import type { SendState } from "./SendState";

export type RoomMessageSummary = { event_id: string, sender: string, 
/**
 * Text-preview/room-list use — kept for backwards compatibility
 * alongside `content`, which carries the full tagged-union payload.
 */
body: string, 
/**
 * `org.matrix.custom.html` formatted body, when the message (or its
 * latest edit) has one — see `formatted_html_body` in this module.
 * `None` for plain-text messages. Rendered only after re-sanitizing
 * against the Matrix-permitted allowlist (`composerSanitize.ts`); never
 * trust this as pre-sanitized just because it came from the SDK.
 */
formatted_body: string | null, timestamp_ms: number, edited: boolean, redacted: boolean, reactions: Array<ReactionGroup>, in_reply_to: ReplyRef | null, transaction_id: string | null, send_state: SendState, 
/**
 * `None` for text/notice/emote messages; `Some` for image/video/audio/file
 * msgtypes. See [`MediaContent`] and `resolve_media` (in `mod.rs`) for
 * how the frontend turns this into an actual displayable/downloadable
 * local path.
 */
media: MediaContent | null, };
