// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmojiPair } from "./EmojiPair";

export type SasUpdateEvent = { "state": "started" } | { "state": "accepted" } | { "state": "keys_exchanged", emojis: Array<EmojiPair>, } | { "state": "confirmed" } | { "state": "done" } | { "state": "cancelled", reason: string, };
