// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchCommandError = { "code": "invalid_query", message: string, } | { "code": "stale_cursor", message: string, } | { "code": "unavailable", message: string, };
