// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMatchRange } from "./SearchMatchRange";

export type SearchResult = { room_id: string, event_id: string, sender: string, origin_server_ts: number, snippet: string, match_ranges: Array<SearchMatchRange>, };
