// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pushed on `profile:self` when the signed-in user's own membership event
 * (in any shared room) carries a changed display name/avatar — see the
 * module doc comment for why this is keyed off a membership event rather
 * than a dedicated profile-change event.
 */
export type SelfProfileUpdate = { display_name: string | null, avatar_url: string | null, };
