// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local send-queue state of a message, folded onto its `RoomMessageSummary`
 * so the frontend can flip a bubble pending -> sent -> error without a full
 * timeline diff. See `send_queue:update` in `actions.rs`, which carries the
 * same shape for out-of-band updates between timeline diffs.
 */
export type SendState = { "state": "pending" } | { "state": "sent" } | { "state": "error", message: string, };
