// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SendState } from "./SendState";

/**
 * Pushed whenever a queued send changes state — a new local echo, a
 * successful send, or an error — so the frontend can flip a bubble
 * pending -> sent -> error without waiting for (or in addition to) a full
 * `timeline:update` diff. Spawned once at login/session-restore time from a
 * `room.send_queue()` (global `SendQueue::subscribe`) listener.
 */
export type SendQueueUpdateEvent = { room_id: string, transaction_id: string, send_state: SendState, };
