// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The standard slash commands the composer's autocomplete menu offers.
 * Mirrors the frontend's static command list (name/args hint/description) —
 * this enum is just the resolved-command wire type, not the help text.
 */
export type SlashCommand = "me" | "topic" | "invite" | "kick" | "ban";
