// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpaceChild } from "./SpaceChild";

/**
 * One node in a recursive space hierarchy. `child` may be a normal room or
 * another space; only space nodes can have non-empty `children`.
 */
export type SpaceHierarchyNode = { child: SpaceChild, children: Array<SpaceHierarchyNode>, };
