// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unread/highlight rollup for a single space.
 */
export type SpaceBadgeState = { 
/**
 * Number of child rooms with `has_unread() == true`.
 */
total_unread: number, 
/**
 * Sum of child-room `unread_count`.
 */
total_highlight: number, };
