// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpaceJoinRule } from "./SpaceJoinRule";

/**
 * One child room summary. The lightweight browser reads one hierarchy page;
 * settings management enumerates every live child edge.
 */
export type SpaceChild = { room_id: string, name: string | null, topic: string | null, num_joined_members: number, join_rule: SpaceJoinRule, is_space: boolean, };
