// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpaceJoinRule } from "./SpaceJoinRule";

/**
 * One child room of a space, as returned by the `/hierarchy` endpoint —
 * Day-1 scope only reads the first page (see module docs), so large spaces
 * show a "load more" affordance instead of paginating automatically.
 */
export type SpaceChild = { room_id: string, name: string | null, topic: string | null, num_joined_members: number, join_rule: SpaceJoinRule, is_space: boolean, };
