// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineStateChange = { "type": "name", old_value: string | null, new_value: string | null, } | { "type": "topic", old_value: string | null, new_value: string | null, } | { "type": "avatar", old_value: string | null, new_value: string | null, } | { "type": "tombstone", body: string | null, replacement_room_id: string | null, } | { "type": "hidden", event_type: string, };
