// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMessageSummary } from "./RoomMessageSummary";
import type { TimelineItemSummary } from "./TimelineItemSummary";

export type TimelinePage = { messages: Array<RoomMessageSummary>, 
/**
 * Full message/state/membership stream for Spec 39 consumers. Kept
 * alongside `messages` so existing message-only surfaces remain stable.
 */
items?: Array<TimelineItemSummary>, 
/**
 * Spec 14 tweak (the one allowed IPC-contract change): with a
 * `matrix-sdk-ui` `Timeline` backing pagination, there's no opaque
 * server-side cursor to resume from any more — `Timeline::paginate_backwards`
 * is stateful per-room (it just walks further back from wherever that
 * room's `Timeline` currently is). So this is now a **sentinel**, not a
 * token: `Some("more")` means the timeline start hasn't been reached yet
 * (call `get_timeline_page` again to page further back), `None` means
 * the start of the room's history has been reached. The frontend already
 * only passes this back opaquely (never reads its value), so this is a
 * same-shape, source-compatible change.
 */
next_cursor: string | null, };
