// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMessageSummary } from "./RoomMessageSummary";

export type TimelinePage = { messages: Array<RoomMessageSummary>, 
/**
 * Pass back as `cursor` to fetch the page further back in history.
 */
next_cursor: string | null, };
