// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMessageSummary } from "./RoomMessageSummary";
import type { TimelineMembershipChange } from "./TimelineMembershipChange";
import type { TimelineStateChange } from "./TimelineStateChange";

/**
 * Additive Spec 39 timeline contract. The existing message-only page/update
 * payload remains unchanged while the frontend rendering and collapse slice
 * migrates to this discriminated union.
 */
export type TimelineItemSummary = { "kind": "message", message: RoomMessageSummary, } | { "kind": "membership", event_id: string, sender: string, timestamp_ms: number, target_user_id: string, target_display_name: string | null, change: TimelineMembershipChange, reason: string | null, } | { "kind": "state", event_id: string, sender: string, timestamp_ms: number, state_key: string, change: TimelineStateChange, };
