// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pushed to the frontend whenever a sync response carries an `m.typing`
 * ephemeral event for a room. `m.typing` is always a full replace (the set
 * of currently-typing users), never a delta, so this event is too.
 */
export type TypingUpdate = { room_id: string, user_ids: Array<string>, };
