// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured error for the four UIA-gated settings commands
 * (`change_password`, `deactivate_account`, `delete_device`,
 * `bootstrap_cross_signing`), carrying the UIA-vs-other distinction
 * `retry_uia_with_session` already computes across the Tauri IPC boundary.
 *
 * `UiaChallenge` means the homeserver wants re-authentication — the
 * frontend should prompt for a password and retry. `Other` means a real,
 * unrelated failure (network error, 500, "not logged in", etc.) — the
 * frontend should surface it as-is, not treat it as a password prompt.
 *
 * Deliberately minimal (two variants) rather than a general error taxonomy
 * — resist splitting `Other` further (e.g. network vs. server error) unless
 * a concrete frontend need shows up.
 */
export type UiaCommandError = { "kind": "UiaChallenge" } | { "kind": "Other", message: string, };
