// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pushed to the frontend as an attachment upload progresses. `sent`/`total`
 * are in bytes. The vendored matrix-rust-sdk (0.18.0) exposes real
 * byte-level upload progress via `SendAttachment::with_send_progress_observable`
 * (an `eyeball::SharedObservable<TransmissionProgress>`), so this carries
 * genuine incremental progress rather than a start/complete-only fabrication
 * — see `send_attachment` below for how it's wired up.
 */
export type UploadProgress = { txn_id: string, room_id: string, sent: number, total: number, };
