// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Frontend-facing preview data for one URL. All fields are best-effort —
 * any of them may be absent depending on what the target page's OpenGraph
 * tags (or the homeserver's fallback scraping) actually provided.
 */
export type UrlPreview = { title: string | null, description: string | null, 
/**
 * `og:image`, as returned by the homeserver. Per the C-S API, this is
 * typically an `mxc://` URI (the homeserver re-hosts the remote image),
 * not a directly-loadable URL — resolve it the same way an avatar mxc
 * URI is resolved (`resolve_avatar`) before use.
 */
imageUrl: string | null, imageWidth: number | null, imageHeight: number | null, siteName: string | null, };
