// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceUpdate } from "./PresenceUpdate";

/**
 * Canonical profile-card read model (Spec 36).
 *
 * Global profile fields and room-scoped membership fields intentionally stay
 * separate: a room display name/avatar can differ from the account-wide
 * profile, and collapsing them would make the UI unable to explain which
 * identity other room members actually see.
 */
export type UserProfile = { user_id: string, display_name: string | null, avatar_url: string | null, avatar_path: string | null, room_display_name: string | null, room_avatar_url: string | null, room_avatar_path: string | null, presence: PresenceUpdate | null, };
