// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerificationRequestSummary = { flow_id: string, other_user_id: string, other_device_id: string, };
