// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recorder metadata shared by native IPC and web multipart attachments.
 */
export type VoiceMessageMetadata = { duration_ms: number, waveform: Array<number>, };
